name: roller_maniac
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  collection: ^1.17.2
  cloud_firestore: 5.6.7
  font_awesome_flutter: ^10.7.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.4.0  # Ajusta a una versión compatible
  http: 1.4.0
  flutter_svg: 2.1.0
  firebase_performance: ^0.10.0+10
  fl_chart: ^1.0.0
  flutter_animate: ^4.5.0
  get_it: 8.0.3
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1  # Solo la versión principal, no las plataformas específicas
  intl: ^0.19.0
  path_provider: ^2.1.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  file_picker: 10.1.9
  archive: 4.0.7
  flutter_pdfview: 1.4.0

dev_dependencies:
  flutter_launcher_icons: 0.14.3

  flutter_lints: ^4.0.0
  lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - img/

flutter_icons:
  android: true
  ios: true
  image_path: "img/logoApp.png"
