name: roller_maniac
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  cached_network_image_platform_interface: ^4.1.1
  cached_network_image_web: ^1.3.1
  collection: ^1.17.2
  firebase_auth: ^5.3.3
  firebase_auth_platform_interface: ^7.4.9
  firebase_auth_web: ^5.13.4
  firebase_core: ^3.8.0
  firebase_core_platform_interface: ^5.3.0
  firebase_core_web: ^2.18.1
  firebase_performance: ^0.10.0+10
  firebase_performance_platform_interface: ^0.1.4+46
  firebase_performance_web: ^0.1.7+4
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.4.1
  font_awesome_flutter: ^10.7.0
  from_css_color: ^2.0.0
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  google_sign_in_android: ^6.1.30
  google_sign_in_ios: ^5.7.7
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4+2
  intl: ^0.19.0
  json_path: ^0.7.2
  page_transition: ^2.1.0
  path_provider: ^2.1.1
  path_provider_android: ^2.2.6
  path_provider_foundation: ^2.3.2
  path_provider_linux: ^2.2.1
  path_provider_platform_interface: ^2.1.2
  path_provider_windows: ^2.2.2
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2
  rxdart: ^0.27.7
  shared_preferences: ^2.3.2
  shared_preferences_android: ^2.3.2
  shared_preferences_foundation: ^2.5.2
  shared_preferences_linux: ^2.4.1
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.2
  shared_preferences_windows: ^2.4.1
  sign_in_with_apple: ^6.1.2
  sign_in_with_apple_platform_interface: ^1.1.0
  sign_in_with_apple_web: ^2.1.0  # CORREGIDO desde 2.2.0 (no existe)
  sqflite: ^2.3.3+1
  sqflite_common: ^2.5.4+3
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  url_launcher_android: ^6.3.10
  url_launcher_ios: ^6.3.1
  url_launcher_linux: ^3.2.0
  url_launcher_macos: ^3.2.1
  url_launcher_platform_interface: ^2.3.2  # CORREGIDO desde 2.3.3 (no existe)
  url_launcher_web: ^2.3.3
  url_launcher_windows: ^3.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - img/

