// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq431CWuM-mYzIqsUBcfSfJwTR5nkZhQ0',
    appId: '1:205515140357:web:885cf49dbe79f1710a5b6c',
    messagingSenderId: '205515140357',
    projectId: 'rollermaniac-a54df',
    authDomain: 'rollermaniac-a54df.firebaseapp.com',
    storageBucket: 'rollermaniac-a54df.firebasestorage.app',
    measurementId: 'G-DXQZ1JXLZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYz9YZrZ9y_RMXWdis91zBuoi5ZqdfhwM',
    appId: '1:205515140357:android:6fa8bd1e39bf66180a5b6c',
    messagingSenderId: '205515140357',
    projectId: 'rollermaniac-a54df',
    storageBucket: 'rollermaniac-a54df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu2NbOawCzUOGmU-24rUnyC1_PtfQ6Xns',
    appId: '1:205515140357:ios:ed33b36b37c38e350a5b6c',
    messagingSenderId: '205515140357',
    projectId: 'rollermaniac-a54df',
    storageBucket: 'rollermaniac-a54df.firebasestorage.app',
    iosBundleId: 'com.example.sergioRollermaniac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu2NbOawCzUOGmU-24rUnyC1_PtfQ6Xns',
    appId: '1:205515140357:ios:ed33b36b37c38e350a5b6c',
    messagingSenderId: '205515140357',
    projectId: 'rollermaniac-a54df',
    storageBucket: 'rollermaniac-a54df.firebasestorage.app',
    iosBundleId: 'com.example.sergioRollermaniac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq431CWuM-mYzIqsUBcfSfJwTR5nkZhQ0',
    appId: '1:205515140357:web:2d8c3451e593988d0a5b6c',
    messagingSenderId: '205515140357',
    projectId: 'rollermaniac-a54df',
    authDomain: 'rollermaniac-a54df.firebaseapp.com',
    storageBucket: 'rollermaniac-a54df.firebasestorage.app',
    measurementId: 'G-PV7EGBBJW1',
  );
}
