class ClimaUtils {
  static String obtenerCiudadParaClima(String nombreParque, double latitud, double longitud, String pais) {
    // Casos específicos conocidos
    final casosEspecificos = {
      'Parque Warner Madrid': 'San Martín de la Vega, Spain',
      'PortAventura Park': 'Salou, Tarragona, Spain',
      'Ferrari Land': 'Salou, Tarragona, Spain',
      'Disneyland Paris': 'Marne-la-Vallée, France',
      'Walt Disney World': 'Orlando, Florida, United States',
      'Universal Studios Hollywood': 'Los Angeles, California, United States',
      'Universal Studios Florida': 'Orlando, Florida, United States',
      'Tokyo Disneyland': 'Tokyo, Japan',
      'Hong Kong Disneyland': 'Hong Kong, China',
      'Shanghai Disneyland': 'Shanghai, China',
      'Europa-Park': 'Rust, Germany',
      'Tivoli Gardens': 'Copenhagen, Denmark',
      'Liseberg': 'Gothenburg, Sweden',
      'Thorpe Park': 'Chertsey, United Kingdom',
      'Alton Towers': 'Staffordshire, United Kingdom',
      'Blackpool Pleasure Beach': 'Blackpool, United Kingdom',
      'Gardaland': 'Castelnuovo del Garda, Italy',
      'Mirabilandia': 'Ravenna, Italy',
      'Efteling': 'Kaatsheuvel, Netherlands',
      'Phantasialand': 'Brühl, Germany',
      'Heide Park': 'Soltau, Germany',
      'Legoland Billund': 'Billund, Denmark',
      'Legoland Windsor': 'Windsor, United Kingdom',
      'Legoland Deutschland': 'Günzburg, Germany',
      'Parc Astérix': 'Plailly, France',
      'Futuroscope': 'Chasseneuil-du-Poitou, France',
      'Puy du Fou': 'Les Epesses, France',
      'Walibi Belgium': 'Wavre, Belgium',
      'Walibi Holland': 'Biddinghuizen, Netherlands',
      'Walibi Rhône-Alpes': 'Les Avenières, France',
      'Six Flags Magic Mountain': 'Valencia, California, United States',
      'Six Flags Great Adventure': 'Jackson, New Jersey, United States',
      'Cedar Point': 'Sandusky, Ohio, United States',
      'Kings Island': 'Mason, Ohio, United States',
      'Busch Gardens Tampa Bay': 'Tampa, Florida, United States',
      'Busch Gardens Williamsburg': 'Williamsburg, Virginia, United States',
      'SeaWorld Orlando': 'Orlando, Florida, United States',
      'SeaWorld San Diego': 'San Diego, California, United States',
      'Knott\'s Berry Farm': 'Buena Park, California, United States',
      'Canada\'s Wonderland': 'Vaughan, Ontario, Canada',
      'La Ronde': 'Montreal, Quebec, Canada',
      'Wonderland Sydney': 'Sydney, New South Wales, Australia',
      'Dreamworld': 'Gold Coast, Queensland, Australia',
      'Movie World': 'Gold Coast, Queensland, Australia',
      'Sea World Gold Coast': 'Gold Coast, Queensland, Australia',
      'Fuji-Q Highland': 'Fujiyoshida, Yamanashi, Japan',
      'Nagashima Spa Land': 'Kuwana, Mie, Japan',
      'Universal Studios Japan': 'Osaka, Japan',
      'Lotte World': 'Seoul, South Korea',
      'Everland': 'Yongin, Gyeonggi, South Korea',
      'Ocean Park': 'Hong Kong, China',
      'Happy Valley': 'Shenzhen, Guangdong, China',
      'Chimelong Paradise': 'Guangzhou, Guangdong, China',
      'Sunway Lagoon': 'Petaling Jaya, Selangor, Malaysia',
      'Universal Studios Singapore': 'Sentosa, Singapore',
      'Adventure World': 'Perth, Western Australia, Australia',
      'Luna Park Sydney': 'Sydney, New South Wales, Australia',
      'Luna Park Melbourne': 'Melbourne, Victoria, Australia',
      'Rainbow\'s End': 'Auckland, New Zealand',
      'Gold Reef City': 'Johannesburg, Gauteng, South Africa',
      'Ratanga Junction': 'Cape Town, Western Cape, South Africa',
      'Six Flags México': 'Mexico City, Mexico',
      'La Feria de Chapultepec': 'Mexico City, Mexico',
      'Xetulul': 'Retalhuleu, Guatemala',
      'Beto Carrero World': 'Penha, Santa Catarina, Brazil',
      'Hopi Hari': 'Vinhedo, São Paulo, Brazil',
      'Playcenter': 'São Paulo, São Paulo, Brazil',
      'Terra Mítica': 'Benidorm, Alicante, Spain',
      'Isla Mágica': 'Seville, Andalusia, Spain',
      'Parque de Atracciones de Madrid': 'COORDS:40.4165,-3.7026',
      'Tibidabo': 'Barcelona, Spain',
      'Siam Park': 'Adeje, Tenerife, Spain',
      'Loro Parque': 'Puerto de la Cruz, Tenerife, Spain',
      'Aqualand': 'Maspalomas, Gran Canaria, Spain',
      'Aqualandia': 'Benidorm, Alicante, Spain',
      'Aquopolis': 'Villanueva de la Cañada, Madrid, Spain',
      'Aquopolis Cullera': 'Cullera, Valencia, Spain',
      'Aquopolis La Pineda': 'Vila-seca, Tarragona, Spain',
      'Aquopolis Villanueva de la Cañada': 'Villanueva de la Cañada, Madrid, Spain',
      'Aquopolis Zaragoza': 'Zaragoza, Spain',
      'Aquopolis Cartaya': 'Cartaya, Huelva, Spain',
      'Aquopolis Costa del Sol': 'Torremolinos, Málaga, Spain',
      'Aquopolis Costa Tropical': 'Almuñécar, Granada, Spain',
      'Aquopolis Costa Dorada': 'La Pineda, Tarragona, Spain',
      'Aquopolis Costa Brava': 'Platja d\'Aro, Girona, Spain',
      'Aquopolis Costa Azul': 'Vilanova i la Geltrú, Barcelona, Spain',
      'Aquopolis Costa del Azahar': 'Oropesa del Mar, Castellón, Spain',
      'Aquopolis Costa de la Luz': 'Conil de la Frontera, Cádiz, Spain',
      'Aquopolis Costa del Maresme': 'Malgrat de Mar, Barcelona, Spain',
      'Aquopolis Costa del Garraf': 'Vilanova i la Geltrú, Barcelona, Spain',
    };

    // Verificar si es un caso específico
    if (casosEspecificos.containsKey(nombreParque)) {
      return casosEspecificos[nombreParque]!;
    }

    // Para parques no específicos, usar coordenadas aproximadas
    return generarCiudadPorCoordenadas(latitud, longitud, pais);
  }

  static String generarCiudadPorCoordenadas(double latitud, double longitud, String pais) {
    // Mapeo de países a ciudades principales
    final Map<String, List<String>> ciudadesPorPais = {
      'United States': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
      'Canada': ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener'],
      'United Kingdom': ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Leeds', 'Sheffield', 'Edinburgh', 'Bristol', 'Cardiff'],
      'Germany': ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig'],
      'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
      'Spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao'],
      'Italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania'],
      'Netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen', 'Almere', 'Breda', 'Nijmegen'],
      'Belgium': ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Leuven', 'Mons', 'Aalst'],
      'Switzerland': ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Winterthur', 'St. Gallen', 'Lucerne', 'Lugano', 'Biel'],
      'Austria': ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'Sankt Pölten', 'Dornbirn'],
      'Sweden': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro', 'Linköping', 'Helsingborg', 'Jönköping', 'Norrköping'],
      'Norway': ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen', 'Fredrikstad', 'Kristiansand', 'Sandnes', 'Tromsø', 'Sarpsborg'],
      'Denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens', 'Vejle', 'Roskilde'],
      'Finland': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio', 'Pori'],
      'Poland': ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice'],
      'Czech Republic': ['Prague', 'Brno', 'Ostrava', 'Plzen', 'Liberec', 'Olomouc', 'Ústí nad Labem', 'České Budějovice', 'Hradec Králové', 'Pardubice'],
      'Hungary': ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs', 'Győr', 'Nyíregyháza', 'Kecskemét', 'Székesfehérvár', 'Szombathely'],
      'Romania': ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Galați', 'Ploiești', 'Brașov', 'Brăila'],
      'Bulgaria': ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora', 'Pleven', 'Sliven', 'Dobrich', 'Shumen'],
      'Greece': ['Athens', 'Thessaloniki', 'Patras', 'Piraeus', 'Larissa', 'Heraklion', 'Peristeri', 'Kallithea', 'Acharnes', 'Kalamaria'],
      'Portugal': ['Lisbon', 'Porto', 'Vila Nova de Gaia', 'Amadora', 'Braga', 'Funchal', 'Coimbra', 'Setúbal', 'Almada', 'Agualva-Cacém'],
      'Ireland': ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda', 'Dundalk', 'Swords', 'Bray', 'Navan'],
      'Japan': ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kyoto', 'Kawasaki', 'Saitama'],
      'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Changwon', 'Seongnam'],
      'China': ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Tianjin', 'Chongqing', 'Chengdu', 'Nanjing', 'Wuhan', 'Xi\'an'],
      'India': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Surat', 'Jaipur'],
      'Thailand': ['Bangkok', 'Chiang Mai', 'Pattaya', 'Phuket', 'Hat Yai', 'Nakhon Ratchasima', 'Udon Thani', 'Khon Kaen', 'Nakhon Si Thammarat', 'Chiang Rai'],
      'Malaysia': ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Johor Bahru', 'Malacca City', 'Alor Setar', 'Miri', 'Kuching'],
      'Singapore': ['Singapore'],
      'Philippines': ['Manila', 'Quezon City', 'Davao City', 'Caloocan', 'Cebu City', 'Zamboanga City', 'Antipolo', 'Pasig', 'Taguig', 'Valenzuela'],
      'Vietnam': ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hai Phong', 'Can Tho', 'Bien Hoa', 'Hue', 'Nha Trang', 'Buon Ma Thuot', 'Vung Tau'],
      'Indonesia': ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Palembang', 'Makassar', 'Tangerang', 'Depok', 'Batam'],
      'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Newcastle', 'Canberra', 'Sunshine Coast', 'Wollongong'],
      'New Zealand': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Napier-Hastings', 'Dunedin', 'Palmerston North', 'Nelson', 'Rotorua'],
      'South Africa': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Kimberley', 'Pietermaritzburg', 'Nelspruit'],
      'Egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Mansoura', 'El-Mahalla El-Kubra', 'Aswan'],
      'Morocco': ['Casablanca', 'Rabat', 'Fez', 'Marrakech', 'Agadir', 'Tangier', 'Meknes', 'Oujda', 'Kénitra', 'Tetouan'],
      'Tunisia': ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan', 'Gabès', 'Bizerte', 'Ariana', 'Gafsa', 'El Mourouj'],
      'Algeria': ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Batna', 'Blida', 'Sétif', 'Chlef', 'Djelfa', 'Sidi Bel Abbès'],
      'Mexico': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Ciudad Juárez', 'León', 'Zapopan', 'Nezahualcóyotl', 'Guadalupe'],
      'Brazil': ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre'],
      'Argentina': ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'Tucumán', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan'],
      'Chile': ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Viña del Mar', 'Temuco', 'Rancagua', 'Talca', 'Arica'],
      'Colombia': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Cúcuta', 'Bucaramanga', 'Pereira', 'Santa Marta', 'Ibagué'],
      'Peru': ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Cusco', 'Chimbote', 'Huancayo', 'Tacna'],
      'Venezuela': ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana', 'Petare', 'Maturín', 'Barcelona', 'Turmero'],
      'Ecuador': ['Guayaquil', 'Quito', 'Cuenca', 'Santo Domingo', 'Machala', 'Durán', 'Manta', 'Portoviejo', 'Loja', 'Ambato'],
      'Bolivia': ['Santa Cruz de la Sierra', 'La Paz', 'El Alto', 'Cochabamba', 'Oruro', 'Sucre', 'Tarija', 'Potosí', 'Sacaba', 'Montero'],
      'Paraguay': ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá', 'Lambaré', 'Fernando de la Mora', 'Limpio', 'Ñemby', 'Encarnación'],
      'Uruguay': ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú', 'Las Piedras', 'Rivera', 'Maldonado', 'Tacuarembó', 'Melo', 'Mercedes'],
    };

    // Obtener ciudades del país
    final ciudades = ciudadesPorPais[pais] ?? [];
    if (ciudades.isEmpty) {
      // Si no hay ciudades específicas para el país, usar el país como fallback
      return pais;
    }

    // Usar las coordenadas para seleccionar una ciudad (método simple)
    final index = ((latitud + longitud).abs() * 1000) % ciudades.length;
    return '${ciudades[index.toInt()]}, $pais';
  }
}